### PR TITLE
Compatible conversion using pens

### PR DESCRIPTION
**Pull request by jamesgk**
How about this, as a start? Based on https://github.com/googlei18n/cu2qu/pull/20#issuecomment-203045145. The combined changes make it look hairier than it is; probably best to look at this one commit at a time.

The biggest issue I can see is that it takes about twice as long to convert as the non-pen approach.

### CODE REVIEW

**Comment by adrientetar** [comment]
> The biggest issue I can see is that it takes about twice as long to convert as the non-pen approach.

Otherwise we could keep the pens for the case where one doesn't care about staying compatible. e.g. I think I could use that in my toolchain to generate TTFs on the fly (converting contours in ufo2ft before they are put into the TTFont).

**Comment by jamesgk** [comment]
Well, I guess we may as well include both this and rf.py (and maybe a dc.py) for now.

**Comment by anthrotype** [comment]
@jamesgk thank you James. I still haven't got the time to properly look into it. I'll get back to you ASAP.

**Comment by jamesgk** [comment]
Can we pull this soon? There are a couple of pending fontmake-related merges (switching from robofab to defcon) which rely on it.

**Comment by anthrotype** [comment]
Sorry, I've been busy with other things.
Actually, there are a few things which I don't like about this approach, but I don't have the time right now to elaborate.. :(
I did some more work locally on this issue, which takes a different approach -- in short, I use pens just to import the glyphs contours data inside cu2qu and to make the converted output available to clients that support the pen protocol; I don't do any in-place modification but leave the job to the clients themselves as the differences between them are several as there's no "glyph protocol" which is comparable to the pen one... --, however this isn't ready to be pushed just yet.
Do you mind waiting a couple of more days or so?
Thanks.

**Comment by jamesgk** [comment]
From what I interpreted from your approach, it does sound better than what I've got in this PR. So feel free to close this and I've opened https://github.com/googlei18n/cu2qu/pull/21 as a start for defcon compatibility.

**Pull request closed without merging**
